
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="mt-12 pb-8">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center text-brand-subtle text-sm">
        <p>
          Generated by a world-class senior frontend React engineer with Gemini.
        </p>
        <p className="mt-1">
          Disclaimer: This is a demo application. Information provided is for illustrative purposes and not financial advice.
        </p>
      </div>
    </footer>
  );
};

export default Footer;
